### ISSUE TITLE
Agregar estilos al formulario de CrearRecorridos

### ISSUE THREAD

**Issue by tarbz2** [GeGeFe/BusquedadelTesoroEspacial#1]
Hola, si te parece útil agregar algo de estilos al formulario de *CrearRecorridos* puedo llegar a agregarle una base.
No soy experto en estilos, pero no he safado de trabajar con ellos y puedo mejorar cómo se ve el formulario al menos como base.

**Comment by GeGeFe** [comment]
Hola. Muchas gracias por comunicarte. Me parece genial. Todo lo que sume es bienvenido. Manejo poco git. No sé como habría que hacer. ¿Me mandas el css y lo agrego o te haces una copia del repositorio y se manda la modificación a través de git directamente como rama o sugerencia, no sé? Si no sabés como lo investigo, sino hacemos como indiques. Muuchas gracias nuevamente.

**Comment by tarbz2** [comment]
Lo ideal en un repositorio entiendo que sería que yo me clone el ropositorio y una vez hechos los cambios genere un pull request. Todo eso entiendo que debería hacerlo yo y vos verías la solicitud y compararías los cambias y aceptarías de ser el caso.
Voy a ver si puedo sólo cambiar lo estético y si eso no rompe nada, pero entiendo que no si no cambio nombres de id en el html

**Comment by GeGeFe** [comment]
Buenísimo. Espero entonces que aparezca la indicación. Estoy muy contento con el proyecto. Probé el juego con varios grupos y es muy linda la respuesta.

**Comment by tarbz2** [comment]
Un comentario aparte, no conviene tener espacios y/o acentos en nombres de carpetas y archivos, quizás haya que modificar el "Versión 2" por algo como "version2" o "Version_2", etc

**Comment by GeGeFe** [comment]
Hola nuevamente. No tuve tiempo hasta ahora para probar lo del selector y no encontré todavía una forma práctica desde VsCodium de probar las pull request. Instalé una extensión y solo me muestra los archivos y sus diferencias. ¿Sabés de alguna forma de descargar aparte de la versión principal una pull request para probarla? Por ahora lo hice a mano archivo por archivo y lo probé aparte y funcionó. Como verás ya fusioné todo. Muchas gracias por tu colaboración.
Vi en el github web que hay algo para manejar versiones. A lo mejor se puede pasar toda la versión 2 ahí. No sé, nunca la usé a esa funcionalidad.
No me dedico profesionalmente a la programación pero me gusta y creo que si está todo lo más prolijo es mejor para todos. Je. Este proyecto es como un tesoro para mi ya que me viene dando muchas satisfacciones y lo quiero mantener lo mejor posible. Es una alegría que haya gente dispuesta a dar una mano. Aunque suene redundante te vuelvo a agradecer.
Saludos y cualquier otra sugerencia es bienvenida.

**Comment by tarbz2** [comment]
Buenas,
Primero, de nada, siempre que pueda aportar algo bienvenido sea :)
Segundo, por lo que entiendo, deberías sólo cambiar en tu VScodium a la rama en la que estuve trabajando (más allá del pull request), y ahí tendrías el entorno con los cambios.
Tercero, lo de la versión no entiendo mucho por qué está la carpeta aparte como para responder correctamente esa duda.
No encuentro en github alguna forma privada de pasarse un correo, pero si querés podemos organizar alguna llamada y ver esas dudas un día de estos, quizás entendiendo más el proyecto pueda ver alguna forma más de colaborar.
Hay que aprovecharme que estoy desempleado, jaja (no necesariamente desocupado)

**Comment by GeGeFe** [comment]
Buenísimo. Yo por ahora tengo estos horarios libres. Mañana jueves entre las 11 y las 15, el viernes después de las 17, el sábado después de las 16 y el domingo casi a cualquier hora. Decime que te queda mejor y hacemos la videollamada.

**Comment by tarbz2** [comment]
Mañana a las 12 hs puedo

**Comment by GeGeFe** [comment]
Dale. Nos vemos mañana entonces por jitsi.

**Comment by tarbz2** [comment]
Acá la sala: https://calls.disroot.org/busquedadeltesoroespacial
